import { useState } from 'react'

// Mock hospital data for GTA Area
const GTA_HOSPITALS = [
  { id: 'mcmaster', name: 'McMaster University Medical Centre', city: 'Hamilton', phone: '905-521-2100' },
  { id: 'hamilton-general', name: 'Hamilton General Hospital', city: 'Hamilton', phone: '905-527-4322' },
  { id: 'st-josephs', name: "St. Joseph's Healthcare", city: 'Hamilton', phone: '905-522-1155' },
  { id: 'toronto-general', name: 'Toronto General Hospital', city: 'Toronto', phone: '416-340-4800' },
  { id: 'sunnybrook', name: 'Sunnybrook Health Sciences Centre', city: 'Toronto', phone: '416-480-6100' },
  { id: 'mt-sinai', name: 'Mount Sinai Hospital', city: 'Toronto', phone: '416-596-4200' },
  { id: 'sick-kids', name: 'SickKids Hospital', city: 'Toronto', phone: '416-813-1500' },
  { id: 'trillium', name: 'Trillium Health Partners', city: 'Mississauga', phone: '905-848-7580' },
  { id: 'brampton-civic', name: 'Brampton Civic Hospital', city: 'Brampton', phone: '905-494-2120' },
  { id: 'markham-stouffville', name: 'Markham Stouffville Hospital', city: 'Markham', phone: '905-472-7000' },
]

const IncidentReport = ({ report }) => {
  const [copied, setCopied] = useState(false)
  const [selectedHospital, setSelectedHospital] = useState(GTA_HOSPITALS[0].id)
  const [showHospitalSelect, setShowHospitalSelect] = useState(false)
  const [sendStatus, setSendStatus] = useState(null) // null | 'sending' | 'sent'

  const getUrgencyColor = (urgency) => {
    switch (urgency?.toLowerCase()) {
      case 'critical': return 'bg-red-500 text-white'
      case 'high': case 'urgent': return 'bg-cyan-600 text-white'
      case 'medium': return 'bg-cyan-500 text-white'
      default: return 'bg-cyan-400 text-white'
    }
  }

  const generateEMSReport = () => {
    const erSummary = report.erSummary || {}
    const simVitals = report.simulatedVitals || {}
    const incident = report.incidentReport || {}
    const imageAnalysis = report.imageAnalysis || {}
    
    return `
════════════════════════════════════════════════════════════════
                    EMS INCIDENT HANDOFF REPORT
                         #${report.reportId || '000'}
════════════════════════════════════════════════════════════════
Generated: ${report.timestamp || new Date().toLocaleString()}
Triage Level: ${erSummary.triageLevel || report.urgency?.toUpperCase() || 'UNKNOWN'}
${report.callEmergency ? '\n⚠️  EMERGENCY SERVICES RECOMMENDED  ⚠️\n' : ''}
────────────────────────────────────────────────────────────────
                        PATIENT ASSESSMENT
────────────────────────────────────────────────────────────────
Chief Complaint: ${erSummary.chiefComplaint || 'Not specified'}
Suspected Injuries: ${erSummary.suspectedInjuries?.join(', ') || 'None identified'}
Body Position: ${imageAnalysis.position || 'Not determined'}
Distress Level: ${imageAnalysis.distressLevel || 'Unknown'}

────────────────────────────────────────────────────────────────
                     VITAL SIGNS (SIMULATED)
────────────────────────────────────────────────────────────────
Heart Rate:        ${simVitals.heartRate || 'N/A'} BPM
Respiratory Rate:  ${simVitals.respiratoryRate || 'N/A'} /min
O2 Saturation:     ${simVitals.oxygenSaturation || 'N/A'}%
Blood Loss Est:    ${simVitals.bloodLoss || 'None'}
Stress Level:      ${simVitals.stressLevel || 'Unknown'}
Shock Risk:        ${simVitals.shockRisk || 'Unknown'}

────────────────────────────────────────────────────────────────
                      IMMEDIATE ACTIONS
────────────────────────────────────────────────────────────────
${report.actions?.map((a, i) => `${i + 1}. ${a}`).join('\n') || 'None specified'}
${report.doNotActions?.length > 0 ? `\nDO NOT:\n${report.doNotActions.map(a => `• ${a}`).join('\n')}` : ''}

────────────────────────────────────────────────────────────────
                      INCIDENT DETAILS
────────────────────────────────────────────────────────────────
Type: ${incident.type || 'Not specified'}
Location: ${incident.location || 'Not specified'}
Time: ${incident.time || 'Not specified'}
Summary: ${incident.summary || 'N/A'}
Follow-up: ${incident.followUp || 'None specified'}

────────────────────────────────────────────────────────────────
                         DISCLAIMER
────────────────────────────────────────────────────────────────
${report.disclaimer || 'All vitals are simulated for demonstration purposes and are not medical measurements. This report is generated by AI and should not replace professional medical assessment.'}

════════════════════════════════════════════════════════════════
                      END OF REPORT
════════════════════════════════════════════════════════════════
    `.trim()
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateEMSReport()).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  const downloadEMSReport = () => {
    const reportText = generateEMSReport()
    const blob = new Blob([reportText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `EMS-Report-${report.reportId || Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const sendToHospital = () => {
    const hospital = GTA_HOSPITALS.find(h => h.id === selectedHospital)
    setSendStatus('sending')
    // Simulate sending (mock)
    setTimeout(() => {
      setSendStatus('sent')
      console.log(`Report sent to ${hospital.name}`)
      setTimeout(() => {
        setSendStatus(null)
        setShowHospitalSelect(false)
      }, 2000)
    }, 1500)
  }

  const speakWithAgent = () => {
    // Mock agent connection
    alert('Connecting you to a live EMS agent...\n\nThis is a demo feature. In production, this would connect to a 24/7 emergency dispatch center.')
  }

  const urgencyStyle = getUrgencyColor(report.urgency || report.erSummary?.triageLevel)
  const simVitals = report.simulatedVitals || {}
  const erSummary = report.erSummary || {}
  const imageAnalysis = report.imageAnalysis || {}

  return (
    <div className="max-w-6xl mx-auto">
      <div className="panel p-6 border-2 border-gray-300">
        {/* Header Row */}
        <div className="flex items-center justify-between mb-4 pb-4 border-b border-border">
          <div className="flex items-center gap-3">
            <div className={`px-3 py-1 rounded-full font-bold text-sm ${urgencyStyle}`}>
              {erSummary.triageLevel || report.urgency?.toUpperCase() || 'UNKNOWN'}
            </div>
            <h2 className="text-xl font-semibold text-text">
              Incident Report #{report.reportId || '000'}
            </h2>
          </div>
          <div className="text-sm text-text-muted">
            {report.timestamp || new Date().toLocaleString()}
          </div>
        </div>

        {/* Emergency Banner */}
        {report.callEmergency && (
          <div className="bg-red-500/15 border border-red-500/40 rounded-lg p-3 mb-4 text-center">
            <span className="text-red-500 font-bold">⚠️ CALL EMERGENCY SERVICES IMMEDIATELY</span>
          </div>
        )}

        {/* Main Grid - 3 columns */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
          
          {/* Column 1: Patient Assessment */}
          <div className="panel p-4 bg-surface-2">
            <h3 className="text-sm font-semibold text-text-muted uppercase mb-3">Assessment</h3>
            <div className="space-y-2 text-sm">
              <div>
                <span className="text-text-dim">Complaint:</span>
                <div className="text-text font-medium">{erSummary.chiefComplaint || 'Not specified'}</div>
              </div>
              <div>
                <span className="text-text-dim">Position:</span>
                <span className="text-text ml-2">{imageAnalysis.position || 'Unknown'}</span>
              </div>
              <div>
                <span className="text-text-dim">Distress:</span>
                <span className={`ml-2 font-medium ${imageAnalysis.distressLevel?.toLowerCase() === 'severe' ? 'text-red-500' : imageAnalysis.distressLevel?.toLowerCase() === 'moderate' ? 'text-orange-500' : 'text-green-500'}`}>
                  {imageAnalysis.distressLevel || 'Unknown'}
                </span>
              </div>
              {imageAnalysis.injuries?.length > 0 && (
                <div>
                  <span className="text-text-dim">Injuries:</span>
                  <div className="text-red-400 text-xs mt-1">{imageAnalysis.injuries.join(', ')}</div>
                </div>
              )}
            </div>
          </div>

          {/* Column 2: Vitals */}
          <div className="panel p-4 bg-surface-2">
            <h3 className="text-sm font-semibold text-text-muted uppercase mb-3 flex items-center gap-2">
              Vitals <span className="text-text-dim font-normal">(Presage Estimate)</span>
              <img src="/images/image.png" alt="Presage" className="h-4 object-contain" />
            </h3>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <div className="text-center p-2 bg-surface rounded">
                <div className="text-xl font-bold text-red-400">{simVitals.heartRate || '--'}</div>
                <div className="text-xs text-text-dim">HR bpm</div>
              </div>
              <div className="text-center p-2 bg-surface rounded">
                <div className="text-xl font-bold text-text">{simVitals.respiratoryRate || '--'}</div>
                <div className="text-xs text-text-dim">RR /min</div>
              </div>
              <div className="text-center p-2 bg-surface rounded">
                <div className="text-xl font-bold text-green-400">{simVitals.oxygenSaturation || '--'}</div>
                <div className="text-xs text-text-dim">SpO2 %</div>
              </div>
              <div className="text-center p-2 bg-surface rounded">
                <div className={`text-sm font-bold ${simVitals.shockRisk?.toLowerCase() === 'high' ? 'text-red-400' : simVitals.shockRisk?.toLowerCase() === 'moderate' ? 'text-orange-400' : 'text-green-400'}`}>
                  {simVitals.shockRisk || '--'}
                </div>
                <div className="text-xs text-text-dim">Shock Risk</div>
              </div>
            </div>
          </div>

          {/* Column 3: Actions */}
          <div className="panel p-4 bg-surface-2">
            <h3 className="text-sm font-semibold text-text-muted uppercase mb-3">Immediate Actions</h3>
            <ul className="space-y-1 text-sm max-h-32 overflow-y-auto">
              {report.actions?.slice(0, 4).map((action, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-green-500 mt-0.5">✓</span>
                  <span className="text-text">{action}</span>
                </li>
              )) || <li className="text-text-dim">No actions specified</li>}
            </ul>
            {report.doNotActions?.length > 0 && (
              <div className="mt-2 pt-2 border-t border-border">
                <div className="text-xs text-red-400 font-medium">DO NOT:</div>
                <ul className="text-xs text-text-dim mt-1">
                  {report.doNotActions.slice(0, 2).map((a, i) => (
                    <li key={i}>• {a}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>

        {/* Summary Row */}
        {(erSummary.suspectedInjuries?.length > 0 || report.incidentReport?.summary) && (
          <div className="panel p-3 bg-surface-2 mb-4 text-sm">
            <span className="text-text-dim">Summary: </span>
            <span className="text-text">
              {report.incidentReport?.summary || erSummary.suspectedInjuries?.join(', ') || 'N/A'}
            </span>
          </div>
        )}

        {/* Disclaimer */}
        <div className="text-xs text-text-dim text-center mb-4">
          ⚠️ All vitals are simulated for demonstration. Not a medical assessment.
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-3 justify-center">
          <button
            onClick={copyToClipboard}
            className="btn-secondary inline-flex items-center gap-2 text-sm px-4 py-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            {copied ? '✓ Copied!' : 'Copy Report'}
          </button>
          <button
            onClick={downloadEMSReport}
            className="btn-primary-cyan inline-flex items-center gap-2 text-sm px-4 py-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download EMS Report
          </button>
          
          {/* Send to Hospital Button */}
          <div className="relative">
            <button
              onClick={() => setShowHospitalSelect(!showHospitalSelect)}
              className="btn-primary-cyan inline-flex items-center gap-2 text-sm px-4 py-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
              </svg>
              {sendStatus === 'sending' ? 'Sending...' : sendStatus === 'sent' ? '✓ Sent!' : 'Send EMS Report'}
            </button>
            
            {/* Hospital Dropdown */}
            {showHospitalSelect && !sendStatus && (
              <div className="absolute bottom-full left-0 mb-2 w-80 panel p-4 shadow-xl z-10">
                <div className="text-xs text-text-dim uppercase tracking-wide mb-3 font-medium">Select Hospital</div>
                <div className="space-y-2 max-h-48 overflow-y-auto mb-3">
                  {GTA_HOSPITALS.map(h => (
                    <label 
                      key={h.id} 
                      className={`flex items-center gap-3 p-3 rounded-lg cursor-pointer transition-colors ${
                        selectedHospital === h.id 
                          ? 'bg-cyan-500/10 border border-cyan-500/30' 
                          : 'bg-surface-2 hover:bg-surface-3 border border-transparent'
                      }`}
                    >
                      <input
                        type="radio"
                        name="hospital"
                        value={h.id}
                        checked={selectedHospital === h.id}
                        onChange={(e) => setSelectedHospital(e.target.value)}
                        className="accent-cyan-500"
                      />
                      <div className="flex-1 min-w-0">
                        <div className="text-sm font-medium text-text truncate">{h.name}</div>
                        <div className="text-xs text-text-dim">{h.city} • {h.phone}</div>
                      </div>
                    </label>
                  ))}
                </div>
                <button
                  onClick={sendToHospital}
                  className="w-full btn-primary-cyan text-sm"
                >
                  Send Report
                </button>
              </div>
            )}
          </div>

          {/* Speak with Agent Button */}
          <button
            onClick={speakWithAgent}
            className="btn-primary-cyan inline-flex items-center gap-2 text-sm px-4 py-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
            </svg>
            Speak with Agent
          </button>
        </div>
      </div>
    </div>
  )
}

export default IncidentReport
